version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"  # Внутренний порт для Django
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - ALLOWED_HOSTS=natalis-domini.ru,localhost,192.144.12.96
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=django-insecure-y8$g$aq1k-t2iptca%((9b6ml6dv7d@(53(*ltvqw14#1h-(v(
      - TG_TOKEN_ACCESS=7673470497:AAH2zHMgzfp3IC1NCQ0L6pQBqaV-lrwC_uo
      - TG_CHAT_ID=651782561
    depends_on:
      - db
      - redis


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data: